### Send POST request with json body
POST http://localhost:8080/developers
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 1,
  "memberId": "Dong",
  "name": "heedong",
  "age": 25
}